### PR TITLE
Checker

### LINKED ISSUE #81: Validate annotation usages
Provide clear error messages when the annotations are used incorrectly.

### PR DESCRIPTION
**Pull request by rickclephas**
Fixes #81

### CODE REVIEW

File: kmp-nativecoroutines-compiler/src/main/kotlin/com/rickclephas/kmp/nativecoroutines/compiler/diagnostics/KmpNativeCoroutinesErrors.kt [hunk 1]
```diff
@@ -0,0 +1,68 @@
...
+    @JvmField
+    val INVALID_COROUTINES_REFINED = DiagnosticFactory0.create<KtElement>(Severity.ERROR)
+    @JvmField
+    val INVALID_COROUTINES_REFINED_STATE = DiagnosticFactory0.create<KtElement>(Severity.ERROR)
+    @JvmField
+    val INVALID_COROUTINES_STATE = DiagnosticFactory0.create<KtElement>(Severity.ERROR)
+    @JvmField
+    val INVALID_COROUTINE_SCOPE = DiagnosticFactory0.create<KtElement>(Severity.ERROR)
+    @JvmField
+    val REDUNDANT_OVERRIDE_COROUTINES = DiagnosticFactory0.create<KtElement>(Severity.ERROR)
```
Comment (rickclephas) [inline kmp-nativecoroutines-compiler/src/main/kotlin/com/rickclephas/kmp/nativecoroutines/compiler/diagnostics/KmpNativeCoroutinesErrors.kt:45]: Should this really be an error?!

Comment (rickclephas) [reply kmp-nativecoroutines-compiler/src/main/kotlin/com/rickclephas/kmp/nativecoroutines/compiler/diagnostics/KmpNativeCoroutinesErrors.kt:45]: At the moment it's actually a valid use case to annotate overrides, e.g. when implementing an interface.
However this isn't ideal so will convert these to a warning instead.
